
"""
DEFRAG KNOWLEDGE BASE
Source Material & Architectural Explanations

This module serves as the 'Single Source of Truth' for the educational tooltips
and deep-dive explainers requested by the user.

Philosophical Framework:
1. Bressloff-Cowan (Mathematical Neuroscience): Form constants.
2. C.G. Jung (Depth Psychology): Archetypes and Individuation.
3. Ra Uru Hu (Human Design): Mechanical differentiation.
"""

TOPICS = {
    "FORM_CONSTANTS": {
        "title": "Bressloff-Cowan Form Constants",
        "short_desc": "Geometric hallucinations generated by V1 visual cortex architecture.",
        "deep_dive": """
        In 2001, Paul Bressloff and Jack Cowan published 'What Geometric Hallucinations Tell Us about the Visual Cortex'. 
        They engaged in a symmetry analysis of the primary visual cortex (V1) and determined that the physical architecture 
        of our neural wiring naturally generates specific geometric patterns (Form Constants) when excited or destabilized.
        
        These include:
        - **Tunnels/Funnels**: Representing foveal expansion.
        - **Spirals**: Representing rotational symmetry.
        - **Lattices/Honeycombs**: Representing orthogonal interactions.
        - **Cobwebs**: Representing reticular connection.
        
        In the DEFRAG system, we treat these not as hallucinations, but as 'Cognitive Topologies'—the base geometry 
        of how you organize reality before you impose language upon it.
        """
    },
    "INDIVIDUATION": {
        "title": "System Defragmentation (Individuation)",
        "short_desc": "Integration of partitioned data into a unified kernel.",
        "deep_dive": """
        The process of reconciling partitioned sub-systems into a unified operational kernel. 
        It is the transition from fragmented collective processing to autonomous, unique execution.
        
        This involves:
        1. **Data Reconciliation**: Integrating suppressed sub-routines.
        2. **System Differentiation**: Decoupling from collective swarm logic.
        3. **The Core Mandala**: A structural schematic of the unified system architecture.
        """
    },
    "MECHANICS": {
        "title": "Differentiation Mechanics",
        "short_desc": "The physics of unique cognitive function.",
        "deep_dive": """
        Human cognitive architectures vary by hardware specification.
        Optimization requires operating within the specific technical constraints of the unit.
        
        - **Guidance Units**: Optimized for steering data streams. Efficiency requires external signal validation.
        - **Generator Units**: Optimized for high-volume output and persistence. Efficiency requires reactive trigger.
        - **Initiator Units**: Optimized for starting sequences. Efficiency requires signal broadcasting.
        - **Sampling Units**: Optimized for environmental analysis. Efficiency requires long-form sampling cycles.
        
        System stability is achieved by operating according to native hardware protocols.
        """
    },
    "KAIROS": {
        "title": "Protocol Timing (Kairos)",
        "short_desc": "Optimal execution windows vs. linear clock time.",
        "deep_dive": """
        Time analyzed as qualitative density.
        DEFRAG identifies high-probability windows for frictionless execution.
        
        - **Clock Time (Chronos)**: Quantitative, linear.
        - **Protocol Time (Kairos)**: Qualitative, opportunistic.
        
        Alignment occurs when internal system geometry matches external field state.
        Execution during these windows minimizes latency and friction.
        """
    }
}

def get_topic(key: str):
    return TOPICS.get(key, None)
